language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install coveralls pep8 pep257
  - python setup.py install
script:
  - pep8 --ignore=E501 ocfl/*.py *.py
  - pep257 ocfl/*.py *.py
  - python setup.py test
after_success:
  - python setup.py coverage
  - coveralls
